### ISSUE TITLE
Webpack + Svelte + Babel Fails in IE11

### ISSUE THREAD

**Issue by Nicholas-Westby** [jakoblind/webpack-autoconf#100]
I select Webpack + Svelte + Babel:

![createapp](https://user-images.githubusercontent.com/5933222/83051103-5da9a880-a002-11ea-8ba6-c1abafd51809.png)

Download the zip, unzip to my local. Run `npm i` and `npm run build-prd`.

When I open in Chrome, I see "Hello world!". When I open in IE11, I see this:

![ie11](https://user-images.githubusercontent.com/5933222/83050849-fc81d500-a001-11ea-9a52-2d510afc6c23.png)

I think IE11 has a problem with this line of code:

```javascript
function P(t,e,n,u,i,f,d=[-1]){
```

Looks like there is a default parameter, which is not supported in IE: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#Browser_compatibility

I'm not a Babel expert (hence my looking at this project to get started quickly), but maybe a plugin is required? https://babeljs.io/docs/en/babel-plugin-transform-parameters

**Comment by jakoblind** [comment]
Most modern apps don't support IE11, so I don't think I will add support for it here. 

I think you are on the right track with the plugin. You might also want to look into configuring the babel-preset-env to support IE11. I wrote a [blog about babel present env](https://blog.jakoblind.no/babel-preset-env-custom-browserlistrc/). It doesn't exactly describe how to do it but might be a ok starting point for further research.

I'm closing this issue, but feel free to keep commenting if there something I can help with

**Comment by Nicholas-Westby** [comment]
Might be a babel bug or something. I set the targets to support older browsers:

![babel-config](https://user-images.githubusercontent.com/5933222/83064794-3d381900-a017-11ea-9959-592273bd588e.png)

And the debug output showed that it was targeting IE8:

![targets](https://user-images.githubusercontent.com/5933222/83064744-25609500-a017-11ea-8fc9-bf42102085ff.png)

And it still seemed to contain that default parameter.

The debug output even showed that it was using `transform-parameters`, which is supposed to handle default parameters: https://babeljs.io/docs/en/babel-plugin-transform-parameters

![transform-parameters](https://user-images.githubusercontent.com/5933222/83065035-a455cd80-a017-11ea-9fd4-2ccd14b44ca1.png)

**Comment by jakoblind** [comment]
I took a closer look now. Let me describe what's going on. When you add svelte (without babel) in createapp.dev you get the following config:

<img width="911" alt="Skärmavbild 2020-05-28 kl  07 09 43" src="https://user-images.githubusercontent.com/399339/83101334-66f24e00-a0b2-11ea-90bc-63b2d06e10c4.png">

That part that is marked in red is the config for svelte. It says that all files ending with `.svelte` should be transpiled by `svelte-loader`. This is actually all you need to run the svelte app. Babel is not needed or used here (or maybe Babel is used by `svelte-loader` under-the-hood somehow but I don't know). When you add Babel in createapp.dev you get the following config:

![image](https://user-images.githubusercontent.com/399339/83101457-ad47ad00-a0b2-11ea-8f2e-3a9b4337042d.png)

Note here that this config says that all files ending in `.js` should be used by `babel-loader`. But in this project we have no `.js` files so babel will actually not be used at all. That means that your babel-present-env config is not used and will not fix the IE11 bug. 

Now to continue the debugging you must look into how to make `svelte-loader` support IE11. I found this [thread that looks useful](https://github.com/sveltejs/svelte/issues/2621). And especially [this comment](https://github.com/sveltejs/svelte/issues/2621#issuecomment-489071454). I would try something like this:

```
const webpack = require("webpack");
const path = require("path");

const config = {
  entry: "./src/index.js",
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "bundle.js"
  },
  module: {
    rules: [
      {
        test: /(\.js)|(\.svelte$)$/,
        loader: "babel-loader",
        options: {
          presets: [
            [
              "@babel/preset-env",
              {
                targets: {
                  browsers: ["ie >= 10"]
                }
              }
            ]
          ],
          sourceType: "unambiguous"
        },
        exclude: /\bcore-js\b/
      },
      {
        test: /\.svelte$/,
        loader: "svelte-loader",
        options: {
          preprocess: require("svelte-preprocess")({})
        }
      }
    ]
  },
  resolve: {
    extensions: [".mjs", ".js", ".svelte"]
  }
};

module.exports = config;
```

I cannot test the code above in IE11 but in theory it could work :)
