### ISSUE TITLE
Problem with HTML webpack plugin

### ISSUE THREAD

**Issue by onlyice** [jakoblind/webpack-autoconf#108]
When HTML webpack plugin is enabled, the config below appears in webpack config:

```javascript
  plugins: [
    new HtmlWebpackPlugin({
      appMountId: 'app',
      filename: 'index.html'
    })
    // ...
  ],
```

The problem is: `appMountId` is not an option of [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin), but an option of [html-webpack-template](https://github.com/jaketrent/html-webpack-template). So an react project with HTML webpack plugin enabled won't work.

A possible fix is using `templateContent` argument (docs [here](https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates)):

```javascript
  plugins: [
    new HtmlWebpackPlugin({
      templateContent: ({htmlWebpackPlugin}) => `
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>${htmlWebpackPlugin.options.title}</title>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>
`,
      filename: 'index.html'
    }),
    // ...
```

**Comment by jakoblind** [comment]
Thanks for reporting! I moved from `html-webpack-template` to `html-webpack-plugin` (https://github.com/jakoblind/webpack-autoconf/commit/e6fc345e130bade6665b2835340983130d5b4b8f#diff-ad8b134dc5da19682fbbdcff2b1a36f0) but I must have missed this critical detail. I will look into if it's possible to move back to `html-webpack-template`. If not, I think your suggestion is the best.

**Comment by terabaud** [comment]
instead of templateContent you can alternatively provide:

```js
new HtmlWebpackPlugin({
  template: 'src/index.html' 
})
```

and add the html in a separate file.

The `filename` option can be omitted as `index.html` is the default anyway.

**Comment by adardesign** [comment]
Please fix

**Comment by jakoblind** [comment]
fixed by @adardesign !
