### ISSUE TITLE
There is a comma added to the plugins array in webpack.config.js

### ISSUE THREAD

**Issue by heartbeatSeries** [jakoblind/webpack-autoconf#158]
I don't know why
![1640159733(1)](https://user-images.githubusercontent.com/64472455/147056527-98963514-60b7-466b-a103-d7b1173a048c.jpg)

**Comment by hta218** [comment]
Same here, took me a few mins to figure out 😄

**Comment by jakoblind** [comment]
Thanks for reporting guys and sorry for the wasted time figuring out the issue. I have pushed a fix!
