### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by jakoblind** [jakoblind/webpack-autoconf#16]
Please discuss :)

**Comment by spartanatreyu** [comment]
This may be tied to typescript support (since Angular 2+ is almost always coded with typescript) but the best vanilla typescript config might not be the same as the best Typescript & Angular 2+ config.

**Comment by mhadaily** [comment]
Webpack configuration for Angular is very tricky, it needs to support Lazyloading and other Angular features.

Also, it's less likely someone starts a project and don't use Angular-CLI, CLI almost supports everything that a frontend project needs to have.  and new CLI is also extendable and support schematics.

**Comment by jakoblind** [comment]
@mhadaily makes a good point. I will close this for now.
