### ISSUE TITLE
Combine with webpack-config-plugins

### ISSUE THREAD

**Issue by jantimon** [jakoblind/webpack-autoconf#26]
Hey @jakoblind 

we tried to prepare reusable plugins for loader configurations.  
Maybe you could use them for webpack-autoconf?

https://github.com/namics/webpack-config-plugins

**Comment by jakoblind** [comment]
Hi @jantimon 

Thanks for your request.
This tool is mainly for new devs who want to learn webpack . That's why I want to keep it simple and only use the most basic and common stuff. Your plugin looks awesome though and looks like a nice alternative to this tool!

//Jakob
