### ISSUE TITLE
Bundle optimizer: Issue loading stats.json

### ISSUE THREAD

**Issue by jourdain** [jakoblind/webpack-autoconf#31]
I was curious to try out your tool and did it on one of my project.
Since you are asking for feedback, here is the stats.json that failed.

[stats.json.zip](https://github.com/jakoblind/webpack-autoconf/files/2566991/stats.json.zip)

If you want to try out building the project, it's available [here](https://github.com/kitware/vtk-js)
But I did it more by curiosity, feel free to close that issue if you don't have the cycles...

**Comment by jakoblind** [comment]
Thank you for sharing your stats.json file. I have made an improvement and now your file works!
