### ISSUE TITLE
Does this support Webpack v1?

### ISSUE THREAD

**Issue by MatthewHerbst** [jakoblind/webpack-autoconf#32]
I ran the command `npx webpack --mode production --profile --json > stats.json` as stated on the website, and when trying to upload the file to the website got:

![image](https://user-images.githubusercontent.com/1287375/48286649-2c1abd80-e41b-11e8-8007-0c43d8cda47c.png)

It doesn't give any more information, either on the website itself or in console. Is there any way to determine what's wrong with the file?

**Comment by jakoblind** [comment]
the tool is for webpack v4, and I have never tried it for webpack v1. if you want you can email the stats.json file on jakob@jakoblind.no and I will look whats wrong. I am closing the issue
