### ISSUE TITLE
React - TypeScript should include typescript, @types/react and @types/react-dom as deps when using Parcel

### ISSUE THREAD

**Issue by methodbox** [jakoblind/webpack-autoconf#47]
This issue occurs when using the web UI.

Currently, when creating a new project using React and selecting TypeScript there are no definitions files installed. Note that I've tried this w/and w/out having React selected first. It simply doesn't get added to the package.json. EDIT - **This is when using Parcel, only.** It appears to work with webpack.

React doesn't include definitions files, they have to be installed from @types.

I haven't taken a look at your code, but I'm sure I could submit a PR to fix this, if the suggestion is agreed upon.

Edit - After discussion below, this appears to be a bug and not intended behavior as it works correctly with webpack.

As of today, the following are added when using webpack (and ***should*** be added with Parcel, too):

```json
// package.json
...
"devDependencies": {
    "typescript": "^3.5.3",
    "@types/react": "^16.8.23",
    "@types/react-dom": "^16.8.4"
}
```

**Comment by methodbox** [comment]
While we're at it it doesn't include TypeScript in the package.json. While this is included in VS Code, that's not the case for all popular editors.

**Comment by jakoblind** [comment]
When I select React and typescript I see that `@types/react`, `@types/react-dom` and `typescript` are added in `package.json`:

<img width="1080" alt="Skärmavbild 2019-07-18 kl  08 22 14" src="https://user-images.githubusercontent.com/399339/61434039-32135780-a935-11e9-8896-5f4372157e3c.png">

Is this not what you see when you select it? Or are you using the CLI?

**Comment by methodbox** [comment]
> When I select React and typescript I see that `@types/react`, `@types/react-dom` and `typescript` are added in `package.json`:
> 
> <img alt="Skärmavbild 2019-07-18 kl 08 22 14" width="1080" src="https://user-images.githubusercontent.com/399339/61434039-32135780-a935-11e9-8896-5f4372157e3c.png">
> 
> Is this not what you see when you select it? Or are you using the CLI?
I am not seeing that. And I didn't know there was a CLI, but I do now and I may use that.

If I just select TypeScript, it updates to a `src/index.ts` and adds a `tsconfig.json`; it doesn't even add TypeScript as a dependency.

Note that you are using webpack. I am using Parcel. It appears to work correctly with webpack. It does not work correctly with Parcel.

I'll update the title and OP to be more clear.

**Comment by jakoblind** [comment]
Thank you for making it more clear. I have followed the [official Parcel docs](https://parceljs.org/typeScript.html) and from that I learned that the `typescript` dependency is installed automatically - you don't have to add it to `package.json`. The docs also don't say to add the types when adding React, but I guess it makes sense to add them anyway? I am not so familiar with typescript, but I guess most people use the types when using React?

**Comment by methodbox** [comment]
@jakoblind Yeah, you actually *need* to add the types.

I’m not sure why you wouldn’t need to add TypeScript, but if you’re using VS Code it’s not 100% necessary unless the version shipping with VS Code isn’t as new as the one you want to use.

I’m not sure how that would work for people not using VS Code, though.

**Comment by jakoblind** [comment]
I added the types!

Parcel doesn't require `typescript` as depedency, it adds it automatically. I know I read this somewhere but can't find it right now :D. It doesn't matter if you use VS code or not. From my understanding, it's best practice to not add it in `package.json` so I'll keep it out for now. I'll close this github issue now, but please feel free to open a new if you find any new info. Thanks!

**Comment by methodbox** [comment]
@jakoblind

Thanks for fixing that so quickly!

Btw I found the reference you’re referring to:  https://parceljs.org/typeScript.html
