### ISSUE TITLE
Cannot use [chunkhash] or [contenthash] for chunk

### ISSUE THREAD

**Issue by DanielWLam** [jakoblind/webpack-autoconf#50]
ERROR in chunk runtime [entry]
[name].[contenthash].js
Cannot use [chunkhash] or [contenthash] for chunk in '[name].[contenthash].js' (use [hash] instead)

![image](https://user-images.githubusercontent.com/8369212/65938925-f62d6000-e456-11e9-9f76-5881d8af3b8a.png)

**Comment by jakoblind** [comment]
I couldn't reproduce this error. Which features did you pick?

**Comment by jacekk** [comment]
I've came across the same error while adding `webpack-dev-server` with the `--hot` flag. Simple 

```json
"scripts": {
    ...
    "start": "webpack-dev-server --hot --mode development"
},
```
causes this error. It is somewhat described in https://stackoverflow.com/a/50217641 .

----

I have a possible solution, so let me prepare a PR that would add support for webpack-dev-server OOTB.
