### ISSUE TITLE
npm script

### ISSUE THREAD

**Issue by Adarsh077** [jakoblind/webpack-autoconf#63]
Add --watch to 'build-dev' script in package.json file 
![image](https://user-images.githubusercontent.com/47920913/67152767-abbc3800-f2cc-11e9-83f4-a07ed0449e3b.jpg)

"build-dev" : "webpack -d --mode development --watch"

**Comment by Adarsh077** [comment]
By the way your online tool is awesome and is very handy. Thank you :) :+1:

**Comment by jakoblind** [comment]
An option to this is to add `webpack-dev-server` in the `start` script as discussed https://github.com/jakoblind/webpack-autoconf/issues/41 . What do you think?

**Comment by Adarsh077** [comment]
Yeah, I think that's the perfect solution.
