### ISSUE TITLE
New feature: html-webpack-plugin

### ISSUE THREAD

**Issue by jakoblind** [jakoblind/webpack-autoconf#64]
By default, there is a hardcoded `index.html` in the `dist` folder. There is a plugin called [HTML webpack plugin](https://github.com/jantimon/html-webpack-plugin) that can generate the `index.html` and is quite commonly used. 

Let's create a new feature group called "Webpack plugins" and add "HTML webpack plugin" to that. The configuration should look similar to the one generated when clicking `code split vendors` feature. 

Also, the `index.html` file should no longer be in the `dist` folder when this feature is clicked

**Comment by vreddy448** [comment]
1) **Html Webpack Plugin Feature** under Webpack plugins Group.
2) when this feature is checked it will update webpack.config.js
3) this feature will help to generate index.html when we do "npm run build-prod" or "npm run build-dev"

<img width="1440" alt="Screen Shot 2019-10-22 at 6 52 09 PM" src="https://user-images.githubusercontent.com/22933940/67289965-1358ca00-f4fd-11e9-9c5a-dbc2a5df388e.png">

**Comment by linus345** [comment]
Looks like this was implemented in #67 and can be closed.
