### ISSUE TITLE
Improve syntax highlighting

### ISSUE THREAD

**Issue by jakoblind** [jakoblind/webpack-autoconf#68]
Improving syntax highlighting as discussed in https://github.com/jakoblind/webpack-autoconf/pull/55. 

Link to @jacekk s WIP: https://github.com/jacekk/webpack-autoconf/pull/1/files

**Comment by jacekk** [comment]
@jakoblind Can you assign me? Not promissing to implement this "today", but I would like get to know PrismJS a bit more :)

**Comment by jakoblind** [comment]
assigned you @jacekk ! :+1:

**Comment by jacekk** [comment]
@jakoblind 
I guess the following issue is related: #23 :)
