### ISSUE TITLE
Parcel/React - Missing babel devDep due to changes w/Babel

### ISSUE THREAD

**Issue by methodbox** [jakoblind/webpack-autoconf#73]
Babel has made some changes that require an additional dev dependency from what is auto-populated on the createapp.dev site.

This also requires an update to your `.babelrc`. 

I've listed the things that need to be changed to make it work, but honestly I haven't done the research to determine why this just suddenly started happening. You might refer to this issue, but it's a year old at this point which again makes me wonder how this just popped up: https://github.com/babel/babel/issues/8655

Add to package.json:

```js
...
"devDependencies": {
...
  "@babel/plugin-proposal-class-properties",
}
```

`.babelrc`:
```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false
      }
    ],
    "@babel/preset-react"
  ],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}
```

I can submit a PR and get this done if you want to give me a head start and point me as to where it might be fixed within your repo.

**Comment by jakoblind** [comment]
From my understanding, this babel plugin is only needed if you're using the [class property syntax](https://babeljs.io/docs/en/next/babel-plugin-proposal-class-properties.html). The example code in  createapp.dev doesn't use this syntax so this plugin is not required to build the projects. 

Have you run into any issues with the generated projects that made you look into this plugin?

**Comment by methodbox** [comment]
> From my understanding, this babel plugin is only needed if you're using the [class property syntax](https://babeljs.io/docs/en/next/babel-plugin-proposal-class-properties.html). The example code in createapp.dev doesn't use this syntax so this plugin is not required to build the projects.
> 
> Have you run into any issues with the generated projects that made you look into this plugin?

That’s correct, but I guess I would assume that most people using React do, at some point, use the class syntax. It may not be necessary for many components, but it’s pretty common. However, I see your point.
