### ISSUE TITLE
.gitignore generated from webapp ignores dist/index.html even though it's not supposed to

### ISSUE THREAD

**Issue by leoncvlt** [jakoblind/webpack-autoconf#75]
This is using the web tool on createapp.dev

When I create a webpack conf, the .gitignore comes out as 
```
...
dist/
!dist/index.html
...
```

Which is meant to ignore bundled webpack files in the dist folder, but allow for index.html - fair. Problem is that this syntax ignores the dist directory itself (so git won't look inside) instead of the files within the directory (which allows for the exclusion). It should be 
``` 
...
dist/*
!dist/index.html
...
```

In order to work.

**Comment by jakoblind** [comment]
agree. if you wanna send a PR, this is the file to update: https://github.com/jakoblind/webpack-autoconf/blob/master/src/templates/base.js#L126 :)

**Comment by jacekk** [comment]
@leoncvlt And I have to disagree. Simple test shows that the `dist` directory is scanned by **git**:
![image](https://user-images.githubusercontent.com/1695878/72559522-44029280-38a5-11ea-9441-c81678fc2f5e.png)

**Comment by leoncvlt** [comment]
> @leoncvlt And I have to disagree. Simple test shows that the `dist` directory is scanned by **git**:

That's because your image shows that your  .gitignore has the right definition, `dist/*` (with the asterisk). I don't know how you scaffolded your code, but If I go to https://createapp.dev/webpack and download the template project, the generated .gitignore has just `dist/` which causes the aforementioned issue.

I'll see if I can get around a PR this weekend :)

**Comment by jacekk** [comment]
@leoncvlt Total failure from my side. I wanted to introduce the change, then I thought I have to test it, so I've tested the altered version, not the original. What a :man_facepalming: . Will test again and create a PR later today :)

**Comment by jakoblind** [comment]
nice! it's merged

**Comment by leoncvlt** [comment]
Thanks both!
