### ISSUE TITLE
Typescript: ts-loader instead awesome-typescript-loader

### ISSUE THREAD

**Issue by wapcrazut** [jakoblind/webpack-autoconf#79]
I've using this app but I saw when Typescript is enabled it adds `awesome-typescript-loader` into `package.json` devDependencies and also it uses this loader into the `webpack.config.js`.

But when I click in the help icon, it shows it will use `ts-loader` (which is preferred):

![image](https://user-images.githubusercontent.com/12850505/74026610-d67aeb00-49a6-11ea-8d13-1e44e56dab40.png)

**Comment by jakoblind** [comment]
PR moving to ts-loader merged
