### ISSUE TITLE
UX/UI suggestion

### ISSUE THREAD

**Issue by thierryc** [jakoblind/webpack-autoconf#80]
UX/UI suggestion

Replace three checkboxes by three radio buttons in the main Library settings. 
The choice is OR not AND. 

Wonderful tools. Thank you for sharing it. 

<img width="233" alt="image" src="https://user-images.githubusercontent.com/197471/74105713-47004400-4b2e-11ea-9e7f-a749c45690b1.png">

**Comment by jakoblind** [comment]
This is a good suggestion. 👍

**Comment by thierryc** [comment]
Thank you.

**Comment by linus345** [comment]
I can give this a try, would you like the inputs to actually be `type="radio"` or keep it as is and only change the styling considering they already act as radio buttons?

**Comment by jakoblind** [comment]
Good point @linus345 . that's also an argument for not style it as a radio button. We would break what a user expects. A user wouldn't expect it to be possible to "deselect" a marked radio button. 

Now I'm leaning towards checkboxes are best of these two solutions. 

Is there a third option?

**Comment by linus345** [comment]
Maybe including "No library" "Vanilla JS" or something similar as an option that is selected by default and have them as radio buttons?

**Comment by jakoblind** [comment]
Good idea. How could I not think of that :D . I like "No library" better. I'm afraid newbies will think "Vanilla JS" is a framework or something. 

Maybe we also should change "Main library" to "View library" or something more describing.

**Comment by linus345** [comment]
”Library / Framework” may be good too, what do you think?

**Comment by linus345** [comment]
If going with radio buttons and the added option "No library" how would you prefer the implementation? To add a new "No library" `feature` and set it to true in `selectedFeatures` when selected(1) **or** to set all main libraries  to false when "No library" is selected(2)? 

**Example 1**
```javascript
selectedFeatures = {
  NoLibrary: true, // new
  React: false,
  Svelte: false,
  Vue: false,
}
```

**Example 2**
```javascript
selectedFeatures = {
  React: false,
  Svelte: false,
  Vue: false,
}
```

Example 2 seems to be what is happening now and would probably need the least amount of change outside of `src/components/configurator/Features.js` but would require to have some kind of conditional rendering inside the `FeatureGroup` component to render the "No library" feature for the "Main library" group.

**Comment by jakoblind** [comment]
Good question. I haven't thought this through in detail yet, but I think example 1 makes the most sense. Add the "No library" feature (it has to be named "No library" and not NoLibrary because this id is used in the UI) in `configurator/webpack-config/index.js` and `configurator/parcel-config/index.js`. This feature will just be empty, something like this:

```
 "No library": {
      group: 'Main library'
  }
``` 

When you add it, it should pop up in the UI. 

The next step is to convert the checkboxes to radios, and as you say it probably involves having some conditional in FeatureGroup component. 

You might also have to change the `selectionRules`. They are used in `pages/index.js`

**Comment by linus345** [comment]
yes I've implemented the styles and conditional for the radio buttons and also added the extra library option just as you did above. It's still not behaving as the other options and I haven't had the time to look at it yet. What's happening now is that when `No library` is selected the previously selected library doesn't get unchecked which probably have something to do with the `selectionRules` as you're suggesting. I'll look at it when I come home.

**Comment by jakoblind** [comment]
Yes exactly, that is what `selectionRules` are for.
