### ISSUE TITLE
Missing App component in React starter

### ISSUE THREAD

**Issue by linus345** [jakoblind/webpack-autoconf#82]
When selecting React as the main library and downloading the zip file `src/index.js` is trying to import the App component from `src/app.js` which currently doesn't exist. This throws the error : 
```
'<path>/empty-project/src/index.js' Cannot resolve dependency './app' at '<path>/empty-project/src/app'
```
To stay consistent with naming conventions it would also be a good idea to change the import from `src/app.js` to `src/App.js` at the same time as this gets fixed.

I can fix this in a PR if needed

**Edit**
Forgot to mention that this is  only for parcel and  **not** webpack

**Comment by jakoblind** [comment]
Thanks for reporting, and it would be awesome if you have time to fix! let me know if you need any assistance. also I agree `src/App.js` is correct naming.
