### ISSUE TITLE
react plugin not mentioned in package.json

### ISSUE THREAD

**Issue by shafkathullah** [jakoblind/webpack-autoconf#85]
react plugin not mentioned in package.json

**Comment by jakoblind** [comment]
could you describe the issue in more detail? I cannot seem to reproduce the issue.

**Comment by shafkathullah** [comment]
![Screenshot 2020-02-24 at 2 02 08 PM](https://user-images.githubusercontent.com/15883435/75137722-570f4a80-570e-11ea-9cd8-ab332d999c1e.png)
Here we need "eslint-plugin-react" in the package.json right? Because we are using it in ".eslintrc" file.

**Comment by jakoblind** [comment]
Yes you are right. I even get the error message when trying to run:

```
jakoblind@MBPsomthorJakob ~/D/empty-project (15)> npx eslint src/*
Failed to load plugin 'react' declared in '.eslintrc.json': Cannot find module 'eslint-plugin-react'
Require stack:
- /Users/jakoblind/Downloads/empty-project (15)/__placeholder__.js
```

Thanks for reporting. This should be fixed!

**Comment by linus345** [comment]
I can fix this if needed.

**Comment by jakoblind** [comment]
that would be great @linus345 !
